# See: https://github.com/pmarsceill/just-the-docs/blob/master/_config.yml
title: linux.brostrend.com
description: BrosTrend WiFi Adapters Linux Support
remote_theme: just-the-docs/just-the-docs@v0.3.3

url: "https://linux.brostrend.com" # the base hostname & protocol for your site, e.g. http://example.com

permalink: pretty
exclude: ["node_modules/", "*.gemspec", "*.gem", "Gemfile", "Gemfile.lock", "package.json", "package-lock.json",  "script/", "LICENSE.txt", "lib/", "bin/", "Rakefile"]

# Set a path/url to a logo that will be displayed instead of the title
logo: "/logo.png"

# Enable or disable the site search
search_enabled: true

# Set the search token separator for hyphenated-word search:
search_tokenizer_separator: /[\s/]+/

# Enable or disable heading anchors
heading_anchors: true

# Aux links for the upper right navigation
aux_links:
  "Main website":
    - "https://www.brostrend.com"

# Footer content appears at the bottom of every page's main content
footer_content: "Copyright &copy; 2018-2025 <a href=\"https://www.brostrend.com\">BrosTrend</a>"

# Color scheme currently only supports "dark" or nil (default)
color_scheme: nil

# Google Analytics Tracking (optional)
# e.g, UA-1234567-89
#ga_tracking: UA-2709176-10

# plugins:
#   - jekyll-seo-tag

compress_html:
  clippings: all
  comments: all
  endings: all
  startings: []
  blanklines: false
  profile: false
